### ISSUE TITLE
add methods for converting to object of normal or numeric form

### ISSUE THREAD

**Issue by haarg** [Perl/version.pm#30]
The methods `normal` and `numify` exist to return the version stringified into those forms of variable. But it would also be good to provide methods that return a version object in either of those forms. This would allow you to change the "primary" form of the version which would be used by stringification, but as a version object, allowing further operations to be done. My initial thought is to name them `to_decimal` and `to_dotted_decimal`, and have them always return new objects. Another possible name would be `to_qv`, to match the currently existing `is_qv` method.

**Comment by Leont** [comment]
This was done in 0.9932
