### ISSUE TITLE
Addition of version objects

### ISSUE THREAD

**Issue by leonerd** [Perl/version.pm#31]
This doesn't work:

```
$ perlsh
eval: v0.1.9 + v0.0.1
Argument "\0\0^A" isn't numeric in addition (+) at (eval 6) line 1.
Argument "\0^A^I" isn't numeric in addition (+) at (eval 6) line 1.
'0'
```

I would have expected the value `v0.1.10`.

**Comment by Leont** [comment]
Vstrings are not numbers, they're strings. People shouldn't be using vstrings in the first place IMNSHO (except for `use v5.24;`). Wanting this in version.pm I can get into, but let's please not do it here.

**Comment by leonerd** [comment]
Ahright, yes I often confuse "vstrings" with "version objects". But you're right - it's more a matter for versions.

```
$ perlsh
eval: version->new("v0.1.9") + version->new("v0.0.1")
ERR: operation not supported with version object at (eval 6) line 1.
```

Point however, remains.

**Comment by haarg** [comment]
I don't think addition of version objects should be supported either. What is the result of `version->new("v0.1.9") + version->new("v0.1.0")`? Is it `v0.2.9`? Does that actually make any sense for a "version"? It's like adding "March 5th" and "February 10th" and getting "May 15th".

**Comment by Leont** [comment]
> I don't think addition of version objects should be supported either. What is the result of version->new("v0.1.9") + version->new("v0.1.0")? Is it v0.2.9? Does that actually make any sense for a "version"? It's like adding "March 5th" and "February 10th" and getting "May 15th".

What is probably necessary though is a `tuple` method returning the components, and arguably some from_tuple method too.

**Comment by Grinnz** [comment]
> > I don't think addition of version objects should be supported either. What is the result of version->new("v0.1.9") + version->new("v0.1.0")? Is it v0.2.9? Does that actually make any sense for a "version"? It's like adding "March 5th" and "February 10th" and getting "May 15th".
> 
> What is probably necessary though is a `tuple` method returning the components, and arguably some from_tuple method too.

Yes, it's always irritating that the only interface to the components is what's documented in version::Internals.

**Comment by rwp0** [comment]
Incrementing versions would not be a bad idea either

```perl
my $version = version -> new('v0.0.1');
...
$version++;
```

**Comment by haarg** [comment]
What do you expect the result of that to be? `v0.0.2` seems like the only thing that makes sense in terms of "incrementing". But `v0.0.1` compares equal to `v0.0.1.0`. So modifying the "last" segment makes it inconsistent. Or would the result be `v1.0.1`? Or `v1.0.0`? None of these are both useful and consistent.

I think any mechanism for modifying a version would only make sense through methods with real names, not overloaded ops. Any it's probably best left out of `version.pm` entirely. This module is meant for representing and comparing versions, not manipulating them. Providing a `tuple` method and a `from_tuple` constructor would allow anyone to build their own tools for manipulating versions.

**Comment by leonerd** [comment]
Fair points all. I think I'll drop this one now.
